name: overwatch_slack_bot
author: P.Y. Laligand
version: 0.0.1
description: A Slack bot for Overwatch communities.
dependencies:
  firebase: 4.0.0
  googleapis_auth: 0.2.3+6
  heroku_slack_bot:
    git:
      url: https://github.com/pylaligand/heroku-slack-bot.git
      ref: master
  http: ^0.11.3+3
  logging: ^0.11.2
